version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pharma_connect
      MYSQL_ROOT_PASSWORD: dou@1994Rna
    ports:
      - 3306:3306
