INSERT INTO `pharmacy` ( `address`, `lat`, `lng`, `name`, `pharmacist`, `city`) VALUES
( 'av. Mly Abdallah , imm. M1 80000 AGADIR', 0, 0, 'Grande Pharmacie d\Agadir', '', 'Agadir'),
	( 'cit? Al Qods , Propri?t? Addakhla, A 508 AGADIR', 0, 0, 'L\Essentiel de la Para Pharmacie', '', 'Agadir'),
( '10, rue d\Ifni , Talborjt AGADIR', 0, 0, 'La G?n?ration de Pharmacie et de Chimie', '', 'Agadir'),
	( '180, av. Imam ElBoukhari , Erac Bouargane AGADIR', 0, 0, 'Pharmacie 20 Aout', '', 'Agadir'),
	( 'av. My Abdellah , r?sid. Karam AGADIR', 0, 0, 'Pharmacie 2000', '', 'Agadir'),
	( '22, av Abderrahim Bouabid , imm. Zerktouni bloc F AGADIR', 0, 0, 'Pharmacie Abousa?d', '', 'Agadir'),
	( 'cit? ElHouda , bloc K n?370 AGADIR', 0, 0, 'Pharmacie Adlouni', '', 'Agadir'),
	( 'hay Mohammadi , cplxe Adoha AGADIR', 0, 0, 'Pharmacie Adoha', '', 'Agadir'),
	( 'complexe Azrou , n?18/17 trance 1 imm.Bicha AGADIR', 0, 0, 'Pharmacie Adouz', '', 'Agadir'),
	( '6, av. Mohammed V , imm. Sabri Rte du Port AGADIR', 0, 0, 'Pharmacie Agadir Oufella', '', 'Agadir'),
	( 'Quartier Tilila , rue Ghaza, imm. Agdal, n?47 AGADIR', 0, 0, 'Pharmacie Agdal', '', 'Agadir'),
	( '95, av. Allal ElFassi , Bouargane AGADIR', 0, 0, 'Pharmacie Agharass', '', 'Agadir'),
	( 'hay Jaanouj Aghroud , bloc C AGADIR', 0, 0, 'Pharmacie Aghroud Bensergao', '', 'Agadir'),
	( 'Hay Mohammadi , n?2934 AGADIR', 0, 0, 'Pharmacie Ait Souss', '', 'Agadir'),
	( 'Hay Al Mohammadi , imm. A1B16 Assafa AGADIR', 0, 0, 'Pharmacie Aiyar', '', 'Agadir'),
	( '2, av Al Mouquaouama , imm. Asma AGADIR', 0, 0, 'Pharmacie Al Andalous', '', 'Agadir'),
	( 'av Abdellah Ibn Yassine bloc 13 n? 17 , bloc 13 n? 17 cit? Sidi Mohamed AGADIR', 0, 0, 'Pharmacie Al Imam AlKastalani', '', 'Agadir'),
	( 'hay Zgoumi Tamraght , Aourir AGADIR', 0, 0, 'Pharmacie Al Wiam', '', 'Agadir'),
	( 'Tamraght - Aourir AGADIR', 0, 0, 'Pharmacie AlBaraka', '', 'Agadir'),
	( 'lot. Tillila parcelle 1340 AGADIR', 0, 0, 'Pharmacie AlBouchra', '', 'Agadir'),
	( '3, av. AlHamra , Amsernat 80000 AGADIR', 0, 0, 'Pharmacie AlHamra', '', 'Agadir'),
	( '114 Bis, av. Hadj Lahbib, les Amicales 80000 AGADIR', 0, 0, 'Pharmacie AlHanaa', '', 'Agadir'),
	( 'bd des Far AGADIR', 0, 0, 'Pharmacie AlHanaa', '', 'Agadir'),
	( 'cit? Salam , rue 952 n?16 AGADIR', 0, 0, 'Pharmacie AlManar', '', 'Agadir'),
	( '61, av Ahmed AlMansour Eddahbi , cit? Dakhla AGADIR', 0, 0, 'Pharmacie AlMansour Eddahbi', '', 'Agadir'),
	( 'bd Cheikh Saadi ang. av des Far AGADIR', 0, 0, 'Pharmacie AlManzah', '', 'Agadir'),
	( 'centre Aourir AGADIR', 0, 0, 'Pharmacie AlMasjid', '', 'Agadir'),
	( '57, avenue Jamal Abdennacer , hay Almassira AGADIR', 0, 0, 'Pharmacie AlMassira', '', 'Agadir'),
	( 'av Abderrahim Bouabid 80000 AGADIR', 0, 0, 'Pharmacie AlMouna', '', 'Agadir'),
	( 'cit? Maalm Ali , bloc B Bensergao AGADIR', 0, 0, 'Pharmacie AlMoustawsaf', '', 'Agadir'),
	( 'Av. Cheikh Saadi, imm. Tighmirt 80000 AGADIR', 0, 0, 'Pharmacie Alamal', '', 'Agadir'),
	( '24 Bis, bd Abdellah Ben Hssa?ne , Cit? Essalam 80000 AGADIR', 0, 0, 'Pharmacie Alikhlass', '', 'Agadir'),
	( 'bd 2 Mars , quartier Amsernat 80000 AGADIR', 0, 0, 'Pharmacie Amsernat', '', 'Agadir'),
	( 'avenue Hassan II , imm. Hasna 80000 AGADIR', 0, 0, 'Pharmacie Anbary', '', 'Agadir'),
	( '10, bd. Mohamed V AGADIR', 0, 0, 'Pharmacie Anezi', '', 'Agadir'),
	( '102, bd. Med Ouazzani, Khiam II 80000 AGADIR', 0, 0, 'Pharmacie Annasr', '', 'Agadir'),
	( '4, Bloc C, Quartier Anza AGADIR', 0, 0, 'Pharmacie Anza', '', 'Agadir'),
	( 'PHARMACIE ALKHATTABI ? 8 PLACE BIR ANZARANE', 0, 0, 'PHARMACIE ALKHATTABI', '', 'bouizakarne'),
	( 'PHARMACIE ALKHATTABI ? AV MOHAMED V', 0, 0, 'PHARMACIE ALKHATTABI', '', 'bouizakarne'),
	( 'PHARMACIE ALKHAWARIZMI ? 8 AVENUE MOHAMED V', 0, 0, 'PHARMACIE ALKHAWARIZMI ', '', 'bouizakarne'),
	( 'PHARMACIE ALMAHATA ? PLACE BANDOENG', 0, 0, 'PHARMACIE ALMAHATA', '', 'Casablanca'),
	( 'PHARMACIE ALMOSTAKBAL ? 1 RUE N 72, IMM. B. HAY SADRI', 0, 0, 'PHARMACIE ALMOSTAKBAL', '', 'Casablanca'),
	( 'PHARMACIE ALMOUHAFADA ? LISSASFA 1, ROUTE D EL JADIDA', 0, 0, 'PHARMACIE ALMOUHAFADA', '', 'Casablanca'),
	( 'PHARMACIE CENTRALE ? LISSASFA II, BLOC D, N 250 B', 0, 0, 'PHARMACIE CENTRALE', '', 'Casablanca'),
	( 'PHARMACIE AZHAR ? 61 AVENUE DEUX MARS', 0, 0, 'PHARMACIE AZHAR', '', 'Casablanca');
/*!40000 ALTER TABLE `pharmacy` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
